language: php

php:
  - 5.4

mysql:
  database: travis_ci_drermahgerd_test
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null

install:
  # install php packages required for running a web server from drush on php 5.4
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # add composer's global bin directory to the path
  # see: https://github.com/drush-ops/drush#install---composer
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc

  # install drush globally
  - composer global require drush/drush:6.*

before_script:

  # navigate out of module directory to prevent blown stack by recursive module lookup
  - cd ../..

  # create a new database
  - mysql -e 'create database travis_ci_drermahgerd_test'

  # create new site, stubbing sendmail path with true to prevent delivery errors and manually resolving drush path
  - php -d sendmail_path=`which true` ~/.composer/vendor/bin/drush.php --yes core-quick-drupal --profile=standard --no-server --db-url=mysql://root:@127.0.0.1/travis_ci_drermahgerd_test --enable=simpletest travis_ci_drermahgerd_test

  # reference drermahgerd module in build site
  - ln -s $(readlink -e $(cd -)) travis_ci_drermahgerd_test/drupal/sites/all/modules/drermahgerd

  # cd into the build site's webroot
  - cd travis_ci_drermahgerd_test/drupal

  # substitute the placeholder token with the path to the current working directory in the behat configuration
  - sed -i "s|%%DRUPAL_ROOT%%|$PWD|" $TRAVIS_BUILD_DIR/tests/behat/behat.yml

  # dl and enable libraries module
  - drush --yes dl libraries
  - drush --yes en libraries

  # dl and enable bad_judgement module
  - drush --yes dl bad_judgement
  - drush --yes en bad_judgement || test true

  # create libraries directory
  - mkdir -p sites/all/libraries

  # dl and extract the Ermahgerd libs into libraries, then rename the directory
  - wget --quiet  --output-document sites/all/libraries/v1.0.3.tar.gz https://github.com/WillSkates/ermahgerd/archive/v1.0.3.tar.gz
  - tar xvzf sites/all/libraries/v1.0.3.tar.gz --directory sites/all/libraries
  - mv sites/all/libraries/ermahgerd-1.0.3 sites/all/libraries/ermahgerd
  # remove the d/l'ed distro tarball
  - rm sites/all/libraries/v1.0.3.tar.gz

  # enable the drermahgerd module
  - drush --yes en drermahgerd

  # install Behat
  - composer install -d $TRAVIS_BUILD_DIR/tests/behat

  # start a web server on port 8080, run in the background; wait for initialization to complete.
  - drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

  # check site status
  - drush status

script:
  # run SimpleTest tests
  - drush test-run 'Drermahgerd' --uri=http://127.0.0.1:8080
  # run Behat tests
  - "(cd $TRAVIS_BUILD_DIR/tests/behat && bin/behat -p travis)"
